<?php
use \Application\Utils\AppHelper;

$form->setAttribute('action', $this->url('admin', ['action' => 'login']));
?>
<h1>Администрирование</h1>

<?php if(!AppHelper::isAuth()) { ?>
    <?= $this->form()->openTag($form);?>
        <div class="row">
            <?= $this->formHidden($form->get('id')); ?>
        </div>
        <div class="row">
            <?= $this->formRow($form->get('login')); ?>
        </div>
        <div class="row">
            <?= $this->formRow($form->get('password')); ?>
        </div>
        <?php if (isset($failMessage)) { ?>
            <div class="row">
                <p class="alert alert-warning"><?= $failMessage?></p>
            </div>
        <?php } ?>
        <div class="row centered">
            <?= $this->formSubmit($form->get('submit')); ?>
        </div>
    <?= $this->form()->closeTag();?>
<?php } else { ?>
    <h2>Список файлов</h2>
    <!-- проблема с CSRF, но пока путь так -->
    <a class="btn btn-default" href="<?= $this->url('admin', ['action' => 'logout'])?>">Выход</a>
    <table>
        <!-- нет паджинации, но пока тоже пусть так -->
        <?php foreach ($files as $file) { ?>
            <tr>
                <td><?= $file->getFileName()?></td>
                <td>
                    <?php
                        $link = $file->getLink();
                        $url = $this->url('files', array('link' => $link));
                    ?>
                    <a href="<?= $url ?>" target="_blank">
                        <?= $url ?>
                    </a>
                </td>
                <td>
                    <?= $file->getProtected() == 1 ? 'защищен паролем' : 'обычное скачивание'?>
                </td>
            </tr>
        <?php } ?>
    </table>
<?php } ?>
