<h1>Администрирование</h1>

<?= $this->form()->openTag($form);?>
    <div class="row">
        <?= $this->formHidden($form->get('id')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('login')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('password')); ?>
    </div>
    <div class="row centered">
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag();?>