<?php
$form->setAttribute('action', $this->url('files', array('action' => 'download', 'link' => $file->getLink())));
?>
<h1>Скачать файл защищенный паролем</h1>
<?= $this->form()->openTag($form);?>
    <?= $this->formHidden($form->get('id')); ?>
    <div class="row">
        <?= $this->formRow($form->get('password')); ?>
    </div>
    <?php if (isset($failMessage)) { ?>
        <div class="row">
            <p class="alert alert-warning"><?= $failMessage?></p>
        </div>
    <?php } ?>
    <div class="row centered">
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag();?>