Application\Entity\Files:
    type: entity
    table: files
    uniqueConstraints:
        link:
            columns:
                - link
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fileName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: file_name
        link:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        protected:
            type: boolean
            nullable: true
            options:
                default: '0'
        pass:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        hash:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
