<h1>Администрирование</h1>
<h2>Список файлов</h2>
<!-- проблема с CSRF, но пока путь так -->
<a class="btn btn-default" href="<?= $this->url('admin', ['action' => 'logout'])?>">Выход</a>
<table>
    <thead>
        <tr>
            <th>Название</th>
            <th>Ссылка</th>
            <th>Размер</th>
            <th>Скачали раз</th>
            <th>Приватность</th>
        </tr>
    </thead>
    <!-- нет паджинации, но пока тоже пусть так -->
    <tbody>
        <?php foreach ($filesProvider as $file) { ?>
            <?php
            /** @var $file \Application\Entity\Files */
            ?>
            <tr>
                <td><?= $file->getFileName()?></td>
                <td>
                    <?php
                    $link = $file->getLink();
                    $url = $this->url('files', array('link' => $link));
                    ?>
                    <a href="<?= $url ?>" target="_blank">
                        <?= $url ?>
                    </a>
                </td>
                <td>
                    <?= $file->getSize(); ?>
                </td>
                <td>
                    <?= $file->getDownloadCount(); ?>
                </td>
                <td>
                    <?= $file->getProtected() == 1 ? 'защищен паролем' : 'обычное скачивание'?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>