<h1>Авторизуйтесь</h1>
<?= $this->form()->openTag($form);?>
    <div class="row">
        <?= $this->formHidden($form->get('id')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('login')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('password')); ?>
    </div>
    <?php if (isset($failMessage)) { ?>
        <div class="row">
            <p class="alert alert-warning"><?= $failMessage?></p>
        </div>
    <?php } ?>
    <div class="row centered">
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag();?>