<?php
$title = 'Расшарить файл';
$this->headTitle($title);
//print $this->showMessages();
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('index', array('action' => 'add')));
$form->prepare();
?>
<?= $this->form()->openTag($form);?>
    <div class="row">
        <?= $this->formHidden($form->get('id')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('name')); ?>
    </div>
    <div class="row">
        <?= $this->formRow($form->get('file')); ?>
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag();?>